import asyncio
import pytest
import os
import json
from logic_engine.orchestrator import AgentOrchestrator
from logic_engine.blackboard import blackboard

@pytest.mark.asyncio
async def test_dvwa_intelligence_correlation():
    """
    Test that the AgentOrchestrator can autonomously correlate 
    findings in DVWA with knowledge from the Obsidian vault.
    """
    
    # 1. Setup
    # Using the default paths which are configured for DVWA and Obsidian vault
    project_name = "dvwa_intelligence_test"
    
    # Allow overriding via command line or env var for testing
    default_repo_path = "/home/kali/Desktop/mac-blm-dast/eval/dvwa"
    repo_path = os.environ.get("TEST_REPO_PATH", default_repo_path)
    
    # If we want to test a specific sub-dir for speed, we can use an env var
    if os.environ.get("TEST_SUBDIR"):
        repo_path = os.path.join(repo_path, os.environ.get("TEST_SUBDIR"))
        
    knowledge_base_path = "/home/kali/Desktop/Qbrain/obsidian_vault"
    
    orchestrator = AgentOrchestrator(
        project_name=project_name,
        repo_path=repo_path,
        knowledge_base_path=knowledge_base_path
    )
    
    # Clear blackboard for a fresh test
    blackboard.clear()
    
    # 2. Define the task
    # We want to see if it finds a vulnerability and correlates it.
    # DVWA has a known SQLi in certain files.
    task = "Scan DVWA for vulnerabilities and correlate findings with the behavior models in the vault."
    
    print(f"\n[*] Starting intelligence correlation test for task: {task}")
    
    # 3. Execute the workflow
    # We'll use a manual state to trigger the graph
    initial_state = {
        "task": task,
        "trace_id": "test-trace-id",
        "original_trace_id": "test-trace-id",
        "target_script": None,
        "target_queue": [],
        "completed_targets": [],
        "context": {
            "discovered_entrypoints": [],
            "technical_context": {},
            "attack_surface": [],
            "knowledge_map": {}
        },
        "blm": {},
        "attack_hypothesis": {},
        "execution_result": {},
        "verdict": {},
        "repro_script": "",
        "findings": [],
        "challenges": [],
        "current_challenge_index": 0,
        "observation": {},
        "next_action": ""
    }
    
    # Run the graph until END
    # We need to use orchestrator.app.ainvoke(initial_state)
    try:
        final_state = await orchestrator.app.ainvoke(initial_state)
        print("[+] Workflow completed successfully.")
    except Exception as e:
        pytest.fail(f"Workflow execution failed: {e}")
        return

    # 4. Verifications
    
    # A. Check if any findings were discovered
    attack_surface = final_state.get("context", {}).get("attack_surface", [])
    print(f"[*] Found {len(attack_surface)} items in attack surface.")
    assert len(attack_surface) > 0, "No attack surface items were discovered."

    # B. Check for correlation (The core requirement)
    # We look for any finding that has 'knowledge_context'
    correlated_findings = [f for f in attack_surface if "knowledge_context" in f]
    print(f"[*] Found {len(correlated_findings)} correlated findings.")
    
    assert len(correlated_findings) > 0, (
        "Intelligence test failed: No findings were correlated with the knowledge vault. "
        "Check if CodebaseScanner is correctly using the knowledge_map and if the Obsidian vault contains relevant AKUs."
    )

    # C. Check if the verdict was generated
    verdict = final_state.get("verdict")
    print(f"[*] Final Verdict: {json.dumps(verdict, indent=2)}")
    assert verdict is not None, "No verdict was generated by the reasoning engine."
    assert "correlation" in verdict.get("summary", "").lower() or "knowledge" in verdict.get("summary", "").lower(), (
        "Verdict does not seem to mention correlation or knowledge. "
        "The reasoning engine might not be using the knowledge_map provided in the context."
    )

    print("[SUCCESS] Intelligence correlation test passed!")

if __name__ == "__main__":
    asyncio.run(test_dvwa_intelligence_correlation())
